### ISSUE TITLE
RESTful API 的一些疑问

### ISSUE THREAD

**Issue by zhaotoday** [ruanyf/articles#13]
您好，看了您的博客关于 RESTful API 的文章，受益匪浅。
我有问题想请教下，比如我有个项目，API 需要提供给 Web 官网、家属 App、员工 App、小程序等不同的子项目用。
这种情况，您是怎么对 API 做分类的，或者说 API 的域名是怎么规划的？

**Comment by ruanyf** [comment]
这个库是存放资料的，不用来咨询。至于你的问题，可以参考数据库设计。
