### ISSUE TITLE
错别字问题

### ISSUE THREAD

**Issue by AnshayM** [ruanyf/articles#14]
台湾大写出版社感觉应该是台湾大学出版社。去搜了搜，发现好像没有找到台湾大写出版社。绿岛真的挺不错的，18年我们毕业旅行去骑行环岛，在那里待了三天。结果潜水台币钱花光了，岛上的ATM机又被取光了，差点回不来，还是找之前消费的地方用信用卡换现金才回得来。
  一直关注着您的动态，有技术的同时也有文化深度，我向您学习。

**Comment by ruanyf** [comment]
确实是大写出版。https://www.andbooks.com.tw/book.php?book_sn=2069
