### ISSUE TITLE
按照你的方法全部试了一遍谷歌云UBUNTU16，在VIM里安"+y复制的内容无法粘贴到系统剪切板

### ISSUE THREAD

**Issue by embeddedsecurity** [ruanyf/articles#15]
在美国蜗牛云VPS服务上提供的UBUNTU16系统，在VIM里安"+y复制的内容可以粘贴到系统剪切板，再从系统剪切板里粘贴到TXT、OFFICE文档，输入:reg也可以看到星号 +号
<img width="824" alt="xshell_ffcbak8s5a" src="https://user-images.githubusercontent.com/24518756/51527017-982f8e00-1e6e-11e9-8016-7cc2aa375652.png">
<img width="949" alt="xshell_tcdltqvqyg" src="https://user-images.githubusercontent.com/24518756/51527074-b8f7e380-1e6e-11e9-880c-ad195931ed8c.png">
谷歌云UBUNTU16，在VIM里安"+y复制的内容无法粘贴到系统剪切板，vim里也没有星号和+号
<img width="892" alt="xshell_luokaxdg8x" src="https://user-images.githubusercontent.com/24518756/51527264-12f8a900-1e6f-11e9-9fa5-ee397ab7d879.png">
<img width="892" alt="xshell_0baniiaisp" src="https://user-images.githubusercontent.com/24518756/51527296-20159800-1e6f-11e9-8f15-2a3cb0ffda0b.png">
在谷歌云UBUNTU16里输入vim --version | grep "clipboard"，clipboard是有+号的
<img width="892" alt="xshell_tigohvoctq" src="https://user-images.githubusercontent.com/24518756/51527711-03c62b00-1e70-11e9-87be-940b0db7cf96.png">

请问我怎么才能在谷歌云UBUNTU16系统，VIM里按ggVG全部复制的内容粘贴到系统剪切板，然后再从系统剪切板里粘贴到txt、office其他程序里？
热心帮助他人的好人一生平安事事顺利心想事成，一夜暴富！

**Comment by ruanyf** [comment]
Vim 复制/粘贴到系统剪贴板，依赖于系统，我也遇到好几次，似乎总有小问题。
