### ISSUE TITLE
博客中的图片无法加载 image.beekka.com 

### ISSUE THREAD

**Issue by Michael18811380328** [ruanyf/articles#18]
早期博客中的图片无法加载 image.beekka.com 一直在loading
<img width="1021" alt="屏幕快照 2019-09-19 15 53 13" src="https://user-images.githubusercontent.com/37589122/65224383-a44f1680-daf5-11e9-953c-9d0c6e6316aa.png">
<img width="591" alt="屏幕快照 2019-09-19 15 52 22" src="https://user-images.githubusercontent.com/37589122/65224384-a4e7ad00-daf5-11e9-9cbd-7acd2af9c1f4.png">

**Comment by ruanyf** [comment]
看官网的版本，这个仓库保存的是草稿。http://www.ruanyifeng.com/blog/2014/12/unicode.html

**Comment by pureliumy** [comment]
官网遇到同样的问题，利用第三方ping工具找到一些CDN节点ip，在hosts中绑定，可以临时解决问题。

**Comment by ruanyf** [comment]
@pureliumy 现在境外还不能打开官网的图床吗？

**Comment by pureliumy** [comment]
不能打开。不过不太清楚公司内网路由规则，所以不知道算不算境外访问，访问谷歌时会自动定向到hk站点。
```bash
traceroute cdn.beekka.com
traceroute: Warning: cdn.beekka.com has multiple addresses; using 119.147.227.100
traceroute to cdn-98hs17m2.slt.sched.tdnsv8.com (119.147.227.100), 64 hops max, 52 byte packets
 1  10.12.115.254 (10.12.115.254)  5.496 ms  2.346 ms  2.856 ms
 2  * * *
 3  *^C
```
