### ISSUE TITLE
想问你的博客文章是用什么框架搭建的？

### ISSUE THREAD

**Issue by robinson90** [ruanyf/articles#2]
如题，是用wordpress还是hexo，自己也想搭建一个，另外想问下写md格式的文件你用的啥，前端的编辑器建议用啥，我现在用的hbuilder，你感觉这个怎么样？ws如何，建议使用么

**Comment by ruanyf** [comment]
用的是 MovableType，如果重做会用 Jekyll。

WordPress 很不错的选择。

**Comment by robinson90** [comment]
hexo如何？我想代码托管在github上，看你的博客文章好像也是和github绑定的，只是样式不同。另外前端开发工具的话，不知道你现在在用哪个？推荐使用啥，我目前用的hbuilder
