### ISSUE TITLE
你好，我想问下你是否通过hexo搭建博客

### ISSUE THREAD

**Issue by robinson90** [ruanyf/articles#3]
我用这个搭建的博客系统，但是发现它把所有的博客都放在一个文件夹了，每个文章里通过分类关键字来区分，这个之后管理很不方便，我想问你下你如果有博客分类的话，不同的文章是混在一起的么？怎么区分。我比较希望的方式是每个文章分类单独一个资源文件夹。

**Comment by ruanyf** [comment]
issue 不是用来咨询的。不过，也确实不了解 hexo。
