### ISSUE TITLE
打扰问您个关于您主页样式的问题

### ISSUE THREAD

**Issue by zhangenming** [ruanyf/articles#8]
偶然发现http://www.ruanyifeng.com/blog/
页面下的$('#homepage_pos > a > img:nth-child(1)')
这个元素的display样式为什么没办法修改
手动把右面    display: none !important;的对勾去掉之后
chrome又会自动把对勾加上
好像有死循环代码在设置$0.style.display='block'一样

本着好奇的心理  一直调试不出来原因
打扰来这里请教   谢谢

<img width="677" alt="screenshot" src="https://user-images.githubusercontent.com/21235555/38129874-63b355ce-3433-11e8-8fc8-fdcccb0dfdb4.png">

$('#homepage_pos > a > img:nth-child(1)')

**Comment by ruanyf** [comment]
这是反广告插件引起的。

**Comment by zhangenming** [comment]
厉害  还真是这样
尴尬
我做了一些前端方面的调试,并没有找到原因
但如果是插件的话就大概能明白了, 
之前没想到这个环节


请问老师您是怎么弄明白这个事情的
我很好奇 
是经验呢 还是做了一些调试

谢谢  谢谢
